version: "3.5"

services:

  flink:
    build: ./flink
    ports:
      - "8081:8081"

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
